title: Juan Zhu's Blog
description: A blog about my experiences and interests.
url: https://eileenzhujuan.github.io/juanzhu/
baseurl: ""
markdown: kramdown

# Add navigation links
navigation:
  - title: index.html
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# - jekyll-feed
# - jekyll-seo-tag
